### ISSUE TITLE
completeAuthorizationRequest does not work without hash routing

### ISSUE THREAD

**Issue by shockron22** [openid/AppAuth-JS#114]
## Expected Behavior
I would expect that completeAuthorizationRequest would be able to get me the code_verifier when I am not using hash routing.
## Describe the problem
https://github.com/openid/AppAuth-JS/blob/master/src/redirect_based_handler.ts#L100

your parse function is hardcoded to use look in location.hash not location.search
https://github.com/openid/AppAuth-JS/blob/master/src/query_string_utils.ts#L30

this means for me completeAuthorizationRequest will NEVER run my AuthorizationListener
#### [REQUIRED] Actual Behavior
my AuthorizationListener never runs. 

#### [REQUIRED] Steps to reproduce the behavior

Attempt to use an AuthorizationListener with an application that does not use location.hash

#### [REQUIRED] Environment

  * AppAuth-JS version: 1.2.4
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...):  Browser
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
You can always override `BasicQueryStringUtils` and override the method to always use `false` if you want. You can then plumb that implementation through to `RedirectBasedHandler` using the constructor.  

https://github.com/openid/AppAuth-JS/blob/master/src/redirect_based_handler.ts#L51

We did this specifically in the sample because users using AppAuth-JS need to consider the downsides of using 3P JavaScript libraries (which have access to the redirect URI).
