### ISSUE TITLE
Include refresh_expires_in in TokenResponse

### ISSUE THREAD

**Issue by vdeygas** [openid/AppAuth-JS#160]
## Expected Behavior
Only expiresIn is take account. 

#### [REQUIRED] Describe expected behavior
We need to know if refresh token is always valid, like the access token. 
This in order to have a session timeout information.

  * AppAuth-JS version:1.3.0
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): Node

**Comment by tikurahul** [comment]
The way this usually works is when you make a subsequent token request with a refresh token your request is invalid. Refresh tokens don't typically expire. If they do (for your provider) you can extend the library like you have done. We don't need to add this to the library itself because this is not typical.
