### ISSUE TITLE
Compile errors when using within another TypeScript project

### ISSUE THREAD

**Issue by juriwiens** [openid/AppAuth-JS#22]
I use this lib within a TS project. When I import the NodeRequestor like in the node_app example and run tsc (version 2.5.2), I get the following compiler errors:

```
node_modules/@openid/appauth/built/node_support/node_requestor.d.ts(1,23): error TS2688: Cannot find type definition file for 'jquery'.
node_modules/@openid/appauth/built/node_support/node_requestor.d.ts(7,22): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/@openid/appauth/built/xhr.d.ts(1,23): error TS2688: Cannot find type definition file for 'jquery'.
node_modules/@openid/appauth/built/xhr.d.ts(6,31): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/@openid/appauth/built/xhr.d.ts(12,22): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/@openid/appauth/built/xhr.d.ts(21,22): error TS2304: Cannot find name 'JQueryAjaxSettings'.
```

I can workaround this by adding the `@types/jquery` module to my project and "dom" to compilerOptions.lib in my tsconfig.json.

I think a solution for this problem would be to move `@types/jquery` from devDependencies to dependencies.

**Comment by tikurahul** [comment]
Yes, this is an oversight. I will go ahead and add this to the list of dependencies. 
I will also go ahead and update the project for TypeScript 2.5.

**Comment by Meligy** [comment]
Since this library is mainly for apps, would it make sense to replace jQuery with [`fetch()`](https://developers.google.com/web/updates/2015/03/introduction-to-fetch)?

Developers still have the ability to replace the Xhr implementation today of course. And a workaround for the issue for now is to set `"skipLibCheck": true` in `tsconfig.json`, which disables errors in NPM packages (but still shows errors in your own code, or when your code interfaces with the package).

**Comment by Meligy** [comment]
The current behaviour with latest TypeScript is that jQuery `settings` shows as `any`, and unless you go to the actual `.d.ts` file you don't get any errors (maybe thanks to existing compiled files).

However, I'll revert `jQuery` especially to keep the full intellisense, so it can be tackled as its own thing.
