### ISSUE TITLE
completeAuthorizationRequestIfPossible should notify on failure?

### ISSUE THREAD

**Issue by someone1** [openid/AppAuth-JS#53]
Right now, if `completeAuthorizationRequestIfPossible` is not able to complete successfully, it just ends without a notification. However, I think it'd make sense to have it notify with a standard error.

**Comment by tikurahul** [comment]
What kind of errors do you want to get notified about ? 

`completeAuthorizationRequestIfPossible()` checks to see if there is a possible response that is waiting to be delivered. Not having a response that is waiting is expected behavior.

Do you want to get notified when the state based and potential PKCE checks fail ?

**Comment by someone1** [comment]
I'd like to know if the attempt was successful or not. My app requires a user is logged in before even loading so I check to see if a user has returned from a redirect and can be logged in, if not, then I try a hidden iFrame with `prompt=none`, and if that fails, I do a standard redirect to the auth page. For all these scenarios, the `completeAuthorizationRequestIfPossible()` doesn't notify if the first two steps fail (it just logs a failure - side note, why are you logging throughout the code and not allowing us to disable this? I have to redirect console.log calls to nothing to disable logging when using in a browser environment - I see the flags.ts file controls something here but as they're exported constants I cannot disable logging).

I just wrote a class that overwrites this functions behavior, but I'd rather not be stomping on anything the library provides.

**Comment by tikurahul** [comment]
`completeAuthorizationRequestIfPossible()` does not notify you because a response is not always present.  This is expected. I log that information because it’s useful in the context of development. You still have not given me information about what you intend to do with the callback you are asking for. If you want to know if the user has logged in - you can always check to see if you have a valid access token. 

As far as eagerly logging goes, I use a Logging redirector throughout the library controlled by `flags`.  The flags are meant to be stripped by your minifier like Closure compiler. That will avoid having to do things like clobbering the console.

**Comment by someone1** [comment]
Sorry if I wasn't clear but I need a failure notification from `completeAuthorizationRequestIfPossible` so I know to redirect my user to login. Again, my app does not wait for user input to initiate a login flow. I cannot check to see if I have an access token because I do not know if `completeAuthorizationRequestIfPossible` is done or not as it [only notifies](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L127) on success - I'd have to wait an arbitrary amount of time and hope that's sufficient for the call to complete before checking to see if I was notified of and obtained an access token. This can be poor user experience and prone to bugs on slower connections. Does that make sense? I don't care what kind of response I get as long as its clear (e.g. by use of a [null response](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L30) or the presence of an [error](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L31)) that it was not able to complete the authorization request (perhaps a seperate function of a more descriptive name is required here, e.g. make `completeAuthorizationRequest` not protected - though this will eliminate the need for the notifier completely in this case).

RE logging - It wasn't immediately clear that was how you can strip it from the code. It just appears to be a [single file](https://github.com/openid/AppAuth-JS/blob/master/src/flags.ts) that [exports](https://github.com/openid/AppAuth-JS/blob/master/src/logger.ts#L15) constant values dicataing the [logic](https://github.com/openid/AppAuth-JS/blob/master/src/logger.ts#L18) of other components. I'll look into this but maybe it makes sense to add this bit to the docs for those of us who are unaware?

I appreciate you taking the time to answer my questions and for this package!

**Comment by tikurahul** [comment]
The client application can control when `compelteAuthorizationRequestIfPossible()` is called. Now this method also returns a `Promise<void>` so you know when the check if complete if you want to do additional checks to see if the user is logged in.

**Comment by someone1** [comment]
Works for me, thank you!
